### PR TITLE
Map swap

### PR DESCRIPTION
**Pull request by katheris**
Create method to swap sites
Create API to swap sites. API is POST /map/v1/swapSites
Add test for API
Add tests for swapping sites over
Add tests for the create API

---
This change is [Reviewable](https://reviewable.io/reviews/gameontext/gameon-map/48)

### CODE REVIEW

**Comment by ebullient** [comment]
Some comments, but I can revisit after.

<details><summary><i>Previously, katheris (Katherine Stanley) wrote…</i></summary>
> #### Map swap
> 
> Create method to swap sites
> 
> Create API to swap sites. API is POST /map/v1/swapSites
> 
> Add test for API
> 
> Add tests for swapping sites over
> 
> Add tests for the create API
> 
> 
> </details>


---

Reviewed 2 of 7 files at r2, 14 of 14 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[map-app/src/main/java/net/wasdev/gameon/map/couchdb/SiteDocuments.java, line 81 \[r3\]](https://reviewable.io:443/reviews/gameontext/gameon-map/48#-KHQNvOonS4BSLOyFuiI:-KHQNvOpX9zj4LEwjkI0:-1097118002) ([raw file](https://github.com/gameontext/gameon-map/blob/3f50575993db62c1d1c852689300d94c733ee4b1/map-app/src/main/java/net/wasdev/gameon/map/couchdb/SiteDocuments.java#L81)):*
> ```Java
> public class SiteDocuments {
>     
>     @Resource(lookup="sweepId")
> ```

Assume this is temporary

---

*[map-app/src/main/java/net/wasdev/gameon/map/couchdb/SiteSwapper.java, line 23 \[r3\]](https://reviewable.io:443/reviews/gameontext/gameon-map/48#-KHQO-NsnZ0HqSW3_w0P:-KHQO-NsnZ0HqSW3_w0Q:-1955047119) ([raw file](https://github.com/gameontext/gameon-map/blob/3f50575993db62c1d1c852689300d94c733ee4b1/map-app/src/main/java/net/wasdev/gameon/map/couchdb/SiteSwapper.java#L23)):*
> ```Java
> import net.wasdev.gameon.map.models.Site;
> 
> public interface SiteSwapper {
> ```

Not sure why this interface is required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-map/48#-:-KHQOLwKUDJu1vmRtf63:169543695)*

**Comment by BarDweller** [comment]
Reviewed 2 of 7 files at r2, 11 of 14 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[map-app/src/main/java/net/wasdev/gameon/map/couchdb/SiteSwapper.java, line 23 \[r3\]](https://reviewable.io:443/reviews/gameontext/gameon-map/48#-KHQO-NsnZ0HqSW3_w0P:-KHQVfhkIjLJYbh7MwHT:217410322) ([raw file](https://github.com/gameontext/gameon-map/blob/3f50575993db62c1d1c852689300d94c733ee4b1/map-app/src/main/java/net/wasdev/gameon/map/couchdb/SiteSwapper.java#L23)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Not sure why this interface is required.</details>
Looks like it's related to the way that the auth privs are granted by the createPolicyForUser thing below... not sure it's entirely obvious at first glance.. looks like the auth stuff expects to be able to restrict access to resources, and access to this interface is used to protect the swapRooms stuff back in MapRepository.. I think it's all a bit odd tho, because this interface is never 'used' as an interface, just as a marker.. It could just have easily been a constant without a method on it ?? (it's forced to be a class by the way 'AccessCertainResourcesPolicy' expects a collection of those)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-map/48)*

**Comment by katheris** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[map-app/src/main/java/net/wasdev/gameon/map/couchdb/SiteDocuments.java, line 81 \[r3\]](https://reviewable.io:443/reviews/gameontext/gameon-map/48#-KHQNvOonS4BSLOyFuiI:-KHU2kS1skqZ6Vb8n1of:1823717445) ([raw file](https://github.com/gameontext/gameon-map/blob/3f50575993db62c1d1c852689300d94c733ee4b1/map-app/src/main/java/net/wasdev/gameon/map/couchdb/SiteDocuments.java#L81)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Assume this is temporary</details>
Good catch, I added this in because I thought I would be using it for auth but didn't use it so I have removed it.

---

*[map-app/src/main/java/net/wasdev/gameon/map/couchdb/SiteSwapper.java, line 23 \[r3\]](https://reviewable.io:443/reviews/gameontext/gameon-map/48#-KHQO-NsnZ0HqSW3_w0P:-KHU38UA3Ei_-Txz6Gi8:1947912022) ([raw file](https://github.com/gameontext/gameon-map/blob/3f50575993db62c1d1c852689300d94c733ee4b1/map-app/src/main/java/net/wasdev/gameon/map/couchdb/SiteSwapper.java#L23)):*
<details><summary><i>Previously, BarDweller wrote…</i></summary>
> Looks like it's related to the way that the auth privs are granted by the createPolicyForUser thing below... not sure it's entirely obvious at first glance.. looks like the auth stuff expects to be able to restrict access to resources, and access to this interface is used to protect the swapRooms stuff back in MapRepository.. I think it's all a bit odd tho, because this interface is never 'used' as an interface, just as a marker.. It could just have easily been a constant without a method on it ?? (it's forced to be a class by the way 'AccessCertainResourcesPolicy' expects a collection of those)</details>
Ozzy is right, I am using it so that I didn't have to refactor the way that 'AccessCertainResourcesPolicy'  works. I'm not sure that it is the most intuitive way to do it, but it means we don't have to have two different systems. It may be that we want to refactor it at some point. I've added a comment on the class to explain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-map/48)*

**Comment by ebullient** [comment]
:lgtm:

<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> Some comments, but I can revisit after.</details>


---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-map/48#-:-KHUTNlvu0yzJwROPAsO:1417088721)*

**Comment by BarDweller** [comment]
Reviewed 1 of 14 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-map/48)*

**Pull request merged**
