### PR TITLE
Store dates, adjust allocating and finding empty sites

### LINKED ISSUE #79: remember date room assigned to site

### PR DESCRIPTION
**Pull request by ebullient**
createdOn, assignedOn; tests, tidying
Partial support for creating a room with a given id
fixes #79 

Signed-off-by: Erin Schnabel <schnabel@us.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gameontext/gameon-map/83)

### CODE REVIEW

**Comment by BarDweller** [comment]
Reviewed 43 of 46 files at r1.
Review status: 30 of 32 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[map-app/src/main/java/org/gameontext/map/db/SiteDocuments.java, line 380 at r1](https://reviewable.io:443/reviews/gameontext/gameon-map/83#-KRycXENfwuz-0X8Sw1s:-KRycXENfwuz-0X8Sw1t:b32vlc) ([raw file](https://github.com/gameontext/gameon-map/blob/47615fd2ad33964ee634543b784fa8f98012a247/map-app/src/main/java/org/gameontext/map/db/SiteDocuments.java#L380)):*
> ```Java
> 
>         db.executeBulk(sites);
>         // checking...
> ```

?

---

*[map-app/src/main/java/org/gameontext/map/model/Site.java, line 73 at r1](https://reviewable.io:443/reviews/gameontext/gameon-map/83#-KRyd2MQ6hfOzR-1kFIi:-KRyd2MQ6hfOzR-1kFIj:b-5f388m) ([raw file](https://github.com/gameontext/gameon-map/blob/47615fd2ad33964ee634543b784fa8f98012a247/map-app/src/main/java/org/gameontext/map/model/Site.java#L73)):*
> ```Java
>     private String owner;
> 
>     /** Date site assigned */
> ```

comment bad?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-map/83)*

**Comment by BarDweller** [comment]
Reviewed 3 of 46 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-map/83)*

**Comment by BarDweller** [comment]
Reviewed 1 of 46 files at r1, 7 of 8 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-map/83)*

**Comment by ebullient** [comment]
Review status: 29 of 30 files reviewed at latest revision, 2 unresolved discussions.

---

*[map-app/src/main/java/org/gameontext/map/db/SiteDocuments.java, line 380 at r1](https://reviewable.io:443/reviews/gameontext/gameon-map/83#-KRycXENfwuz-0X8Sw1s:-KS7V3GwhTG5SS-jxcen:b-j5qw95) ([raw file](https://github.com/gameontext/gameon-map/blob/47615fd2ad33964ee634543b784fa8f98012a247/map-app/src/main/java/org/gameontext/map/db/SiteDocuments.java#L380)):*
<details><summary><i>Previously, BarDweller (Ozzy Osborne) wrote…</i></summary>
> ?
</details>
Old. Not relevant to this review.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-map/83)*

**Comment by BarDweller** [comment]
Reviewed 1 of 46 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-map/83)*

**Pull request merged**
